os:
- linux
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libstdc++6
    - fonts-droid
branches:
  only:
  - master
git:
  depth: false
cache:
  bundler: true
  directories:
  - "$HOME/.pub-cache"
env:
  global:
  - secure: nn/Kq66oJMvxdzOZhycrMXMf7TReON7CW7OQD/9iTYA+hDDfNld0zOGpjg72gCz3kdt88uhzH5IhZMM32d4hU+csJfkQOjK4DWnR7sT3s4Uevku4ENLmQ5FqmKsfj7q0g49/1SWaE/ih7blrYFYuXl1tTu/AUoOCbc+WqtDpDxHCP6p0svTNPw1Izca4N9UEC2rjWCM/lj36y9MwQSjO4vdcJAfCzZ+SYNfawz66blWu9K8RB84kMi4BATH1OhCJm3xXRuztHCl6Q7jsbVk4IH4CTdaA/kAvea1EOq5L32kN3hEQKAX7Ik8uKfoWJJNqHg9YOQ2rFlv49aNafqXMozpQP4GIF84cdamEIduGwSGAfdkF7nuFiuAt5MAaByUvV9r6Y5aiIT/9UGt2fEfrTeDIpx1sYkrHV85x5bqMBFLOamCSrvNfTKREyzwgO9fsdhzaQKA5qkteEj2ukXUqZz8alKhD6961J7ivK7vInIRRDKq0KAU70uQwU1Gt2njmk3rtjd50tdDo7htRSUq8iiC/1R+mEdyZHigTT+hVIzyeO6LxuThwnMmjHuJvUkh/n7WkW71l39CpaH0mJuDY3ov2cR1cqJGEyYpHTC9LV6teMs3agufRg+Jk0K5iRz62DNanRw+bVZ63h8kAyi8SRAY0EFRolNDwvA3aMygYsuQ=
  - secure: DCoI4+caV+XQ/br8B85iMgM6GUPpV2DhZgp4O0skhWzyxWzAwhrPBUzkKGs94OSvYCpSnhZ0LpHicYWfSjtS0fQsUvgMhOTn3Dwys/7FGwZIuM4qnNcanu61UKOt78p0vuDDmZqqIlACe+kVUfC6vbluMViGpEC39DqB3kQEunMvPIT7A4ruiw335MxjDaG1fF6X3VPSee7iDRj1JQXzC14zFGj/3n0Bx1HxiTic1yenuuMSJjNgX1gjzH3CRZk43f45PkY6Mq8kZPEOIYW7bQEmBXe0H4FU8IrRgb1dfvLAYO8nhRHA09v2MFWYsGP+Lw/vaotJVSZtNcOQcV3H33nwzimDZW5+oOuBfFQ9Sl/KbI725GYh5+DPvpDvhCS3G2Zr1IqemO+Cds7ohRNUlcU9ET7KWS7G61h/SdmSjALz9ZAvGXRijkQ84qZcRnofbjbKZiB2iXq+RVPSi2ylPQMianGkAfIGOvMP07MLYGI+hugl1dDfwEHPzNMHWyyUmO8Jg3pxAUF2Tr9ZAu70s5sJF7WAO6bdzpm3lec20KcT97O12s8oobqC7Mhubn/f+GNlBEpuTlGXONR+NCivgGMN8PGEsSPG+tRYV70Wm7Jc//p2pR+PWpHnR22PkKLdYtUlgntowQCwSCFYOgXFr1dKZKrfARrhHERGW1mldeo=
  - secure: fZUkMfTqFiBQspoQuDi6WR3wX3x+cdyrA5CyCrZlCfYAZAOWtq9IDEYD2sYUsN6tCBjEPPlU2h7zbwPy9Tl/MBBaBDyQSlRzYrCW92EwR/QcJcCEgHcoqfzsvLr9rCKQbsn43++Lebn5wXDcPr48L8ZfoCu1wzLnJCxr0tmqu8hJpey+pJimRsdFDeNsYducj3EPqYuRr0t6QbM1pvv+Fc3BsE1Z2hjSk9/uS7h+gTMlr1hVcs3Mg48OtA6P35jV1JF7qbwuyI6zTtzNRlT14Y0eMdLJPW7NZ4RcDnT289I6jJz4rY8oOW4EkL5FBR/su0UDQp1zemNIi7OK0kLK2rftCNMswx0jmLICcp9y15NW6tgtYbTiMCdECW3g9E1CewrhloC8XHCGTLfcVogiUQDOGQppl4D1MlNzu58DwLjrcyL2LTymOZyyIvl6CJavz4LqzMkuTLQDYpXZh0GGyw8Z6KHjibK/cMJ3XtaoPI/prc26ht2IsC/9/IIq4mftZQoZ1uW7OgkCWcjhFoDWUFmzBSweGRClWITJsv7OgyvfcWXPHCQj93QzyWkNDN3N8n1NSij/06vVM4IUF6Q4nlu5O+YaMzgfrUjV3OlMjw5xsdqXds2qReG5IWo5hbi5KBqjPHcF68KoD+olC1fuu8P8S3fXlYIu6oPPSWGWAuI=
before_install:
- openssl aes-256-cbc -K $encrypted_6a8b4a3874cb_key -iv $encrypted_6a8b4a3874cb_iv
  -in catbox.jks.enc -out catbox.jks -d
before_script:
- git clone https://github.com/flutter/flutter.git -b beta --depth 1
- "./flutter/bin/flutter doctor"
- "./flutter/bin/flutter packages get"
- gem install coveralls-lcov
script:
- ulimit -S -n 2048
- "./flutter/bin/flutter analyze lib/ test/"
- "./flutter/bin/flutter test --coverage"
after_success:
- coveralls-lcov coverage/lcov.info
- "./ci/setup.sh"
- "./ci/build.sh"
after_failure:
- coveralls-lcov coverage/lcov.info