os:
  - linux
sudo: false
addons:
  apt:
    # Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
    sources:
      - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
    packages:
      - libstdc++6
      - fonts-droid
cache:
  bundler: true
  directories:
    - $HOME/.pub-cache
before_script:
  - git clone https://github.com/flutter/flutter.git -b beta --depth 1
  - ./flutter/bin/flutter doctor
  - ./flutter/bin/flutter packages get
  - gem install coveralls-lcov
script:
  - ./flutter/bin/flutter analyze lib/ test/
  - ./flutter/bin/flutter test --coverage
after_success:
  - coveralls-lcov coverage/lcov.info
after_failure:
  - coveralls-lcov coverage/lcov.info