name: catbox
description: View cats that are up for adoption.

dependencies:
  flutter:
    sdk: flutter

  http: "^0.11.3+16"
  #cloud_firestore: "0.3.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.2.0"

flutter_icons:
  image_path: "assets/icon.png"
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - images/profile_header_background.png
    - images/portfolio_1.jpeg
    - images/portfolio_2.jpeg
    - images/portfolio_3.jpeg
    - images/portfolio_4.jpeg
    - images/portfolio_5.jpeg
    - images/portfolio_6.jpeg
